print("[̲̅D][̲̅E][̲̅V]  [̲̅B][̲̅Y]  [̲̅C][̲̅O][̲̅N][̲̅D][̲̅O][̲̅R]")




a = input("inserisci nome: ")
b = input("inserisci cognome: ")
c = input("inserisci numeri che potrebbe avere nella password se non ne sai nessuno metti /: ")
d = input("inserisci sopranome: ")
e = input("inserisci anno di nascita: ")
f = input("inserisci nome di cane o qualcuno a lui speciale (solo uno): ")
print("----------------ECCO A TE IL TUO DIZIONARIO PER UN ATTACCO BRUTEFORCE----------------")
if c == "/":
    print(a+ b)
    print(b+ a)
    print(    a+ b+ d)
    print(    a+ d+ b)
    print(    b+ a+ d)
    print(    b+ d+ a)
    print(    d+ a+ b)
    print(    d+ b+ a)
    print(    a+ b+ d+ e)
    print(    a+ b+ e+ d)
    print(    a+ d+ b+ e)
    print(    a+ d+ e+ b)
    print(    a+ e+ b+ d)
    print(    a+ e+ d+ b)
    print(    b+ a+ d+ e)
    print(    b+ a+ e+ d)
    print(    b+ d+ a+ e)
    print(    b+ d+ e+ a)
    print(    b+ e+ a+ d)
    print(    b+ e+ d+ a)
    print(    d+ a+ b+ e)
    print(    d+ a+ e+ b)
    print(    d+ b+ a+ e)
    print(    d+ b+ e+ a)
    print(    d+ e+ a+ b)
    print(    d+ e+ b+ a)
    print(    e+ a+ b+ d)
    print(    e+ a+ d+ b)
    print(    e+ b+ a+ d)
    print(    e+ b+ d+ a)
    print(    e+ d+ a+ b)
    print(    e+ d+ b+ a)
    print(    a+ b+ d+ e+ f)
    print(    a+ b+ d+ f+ e)
    print(    a+ b+ e+ d+ f)
    print(    a+ b+ e+ f+ d)
    print(    a+ b+ f+ d+ e)
    print(    a+ b+ f+ e+ d)
    print(    a+ d+ b+ e+ f)
    print(    a+ d+ b+ f+ e)
    print(    a+ d+ e+ b+ f)
    print(    a+ d+ e+ f+ b)
    print(    a+ d+ f+ b+ e)
    print(    a+ d+ f+ e+ b)
    print(    a+ e+ b+ d+ f)
    print(    a+ e+ b+ f+ d)
    print(    a+ e+ d+ b+ f)
    print(    a+ e+ d+ f+ b)
    print(    a+ e+ f+ b+ d)
    print(    a+ e+ f+ d+ b)
    print(    a+ f+ b+ d+ e)
    print(    a+ f+ b+ e+ d)
    print(    a+ f+ d+ b+ e)
    print(    a+ f+ d+ e+ b)
    print(    a+ f+ e+ b+ d)
    print(    a+ f+ e+ d+ b)
    print(    b+ a+ d+ e+ f)
    print(    b+ a+ d+ f+ e)
    print(    b+ a+ e+ d+ f)
    print(    b+ a+ e+ f+ d)
    print(    b+ a+ f+ d+ e)
    print(    b+ a+ f+ e+ d)
    print(    b+ d+ a+ e+ f)
    print(    b+ d+ a+ f+ e)
    print(    b+ d+ e+ a+ f)
    print(    b+ d+ e+ f+ a)
    print(    b+ d+ f+ a+ e)
    print(   b+ d+ f+ e+ a)
    print(    b+ e+ a+ d+ f)
    print(    b+ e+ a+ f+ d)
    print(    b+ e+ d+ a+ f)
    print(    b+ e+ d+ f+ a)
    print(    b+ e+ f+ a+ d)
    print(    b+ e+ f+ d+ a)
    print(    b+ f+ a+ d+ e)
    print(    b+ f+ a+ e+ d)
    print(    b+ f+ d+ a+ e)
    print(    b+ f+ d+ e+ a)
    print(    b+ f+ e+ a+ d)
    print(    b+ f+ e+ d+ a)
    print(    d+ a+ b+ e+ f)
    print(    d+ a+ b+ f+ e)
    print(    d+ a+ e+ b+ f)
    print(    d+ a+ e+ f+ b)
    print(    d+ a+ f+ b+ e)
    print(    d+ a+ f+ e+ b)
    print(    d+ b+ a+ e+ f)
    print(    d+ b+ a+ f+ e)
    print(    d+ b+ e+ a+ f)
    print(    d+ b+ e+ f+ a)
    print(    d+ b+ f+ a+ e)
    print(    d+ b+ f+ e+ a)
    print(    d+ e+ a+ b+ f)
    print(    d+ e+ a+ f+ b)
    print(   d+ e+ b+ a+ f)
    print(    d+ e+ b+ f+ a)
    print(   d+ e+ f+ a+ b)
    print(    d+ e+ f+ b+ a)
    print(    d+ f+ a+ b+ e)
    print(    d+ f+ a+ e+ b)
    print(    d+ f+ b+ a+ e)
    print(    d+ f+ b+ e+ a)
    print(    d+ f+ e+ a+ b)
    print(    d+ f+ e+ b+ a)
    print(    e+ a+ b+ d+ f)
    print(    e+ a+ b+ f+ d)
    print(    e+ a+ d+ b+ f)
    print(    e+ a+ d+ f+ b)
    print(    e+ a+ f+ b+ d)
    print(    e+ a+ f+ d+ b)
    print(    e+ b+ a+ d+ f)
    print(    e+ b+ a+ f+ d)
    print(    e+ b+ d+ a+ f)
    print(    e+ b+ d+ f+ a)
    print(    e+ b+ f+ a+ d)
    print(    e+ b+ f+ d+ a)
    print(    e+ d+ a+ b+ f)
    print(    e+ d+ a+ f+ b)
    print(    e+ d+ b+ a+ f)
    print(    e+ d+ b+ f+ a)
    print(    e+ d+ f+ a+ b)
    print(    e+ d+ f+ b+ a)
    print(    e+ f+ a+ b+ d)
    print(    e+ f+ a+ d+ b)
    print(    e+ f+ b+ a+ d)
    print(    e+ f+ b+ d+ a)
    print(    e+ f+ d+ a+ b)
    print(    e+ f+ d+ b+ a)
    print(    f+ a+ b+ d+ e)
    print(    f+ a+ b+ e+ d)
    print(    f+ a+ d+ b+ e)
    print(    f+ e+ a+ d+ b)
    print(    f+ e+ b+ a+ d)
    print(    f+ e+ b+ d+ a)
    print(    f+ e+ d+ a+ b)
    print(    f+ e+ d+ b+ a)
else:
    print(a+ b)
    print(    b+ a)
    print(    a+ b+ c)
    print(    a+ c+ b)
    print(    b+ a+ c)
    print(    b+ c+ a)
    print(    c+ a+ b)
    print(    c+ b+ a)
    print(    a+ b+ c+ d)
    print(    a+ b+ d+ c)
    print(    a+ c+ b+ d)
    print(   a+ c+ d+ b)
    print(    a+ d+ b+ c)
    print(    a+ d+ c+ b)
    print(    b+ a+ c+ d)
    print(    d+ b+ a+ c)
    print(    d+ b+ c+ a)
    print(    d+ c+ a+ b)
    print(    d+ c+ b+ a)
    print(    a+ b+ c+ d+ e)
    print(    a+ b+ c+ e+ d)
    print(    a+ b+ d+ c+ e)
    print(    a+ b+ d+ e+ c)
    print(    a+ b+ e+ c+ d)
    print(    a+ b+ e+ d+ c)
    print(    a+ c+ b+ d+ e)
    print(    a+ c+ b+ e+ d)
    print(    a+ c+ d+ b+ e)
    print(    a+ c+ d+ e+ b)
    print(    a+ c+ e+ b+ d)
    print(    a+ c+ e+ d+ b)
    print(    a+ d+ b+ c+ e)
    print(    a+ d+ b+ e+ c)
    print(    a+ d+ c+ b+ e)
    print(    a+ d+ c+ e+ b)
    print(    a+ d+ e+ b+ c)
    print(    a+ d+ e+ c+ b)
    print(    a+ e+ b+ c+ d)
    print(    a+ e+ b+ d+ c)
    print(    a+ e+ c+ b+ d)
    print(    a+ e+ c+ d+ b)
    print(    a+ e+ d+ b+ c)
    print(    a+ e+ d+ c+ b)
    print(    b+ a+ c+ d+ e)
    print(    b+ a+ c+ e+ d)
    print(    b+ a+ d+ c+ e)
    print(    b+ a+ d+ e+ c)
    print(    b+ a+ e+ c+ d)
    print(    b+ a+ e+ d+ c)
    print(    b+ c+ a+ d+ e)
    print(    b+ c+ a+ e+ d)
    print(    b+ c+ d+ a+ e)
    print(    b+ c+ d+ e+ a)
    print(    b+ c+ e+ a+ d)
    print(    b+ c+ e+ d+ a)
    print(    b+ d+ a+ c+ e)
    print(    b+ d+ a+ e+ c)
    print(    b+ d+ c+ a+ e)
    print(    b+ d+ c+ e+ a)
    print(    b+ d+ e+ a+ c)
    print(    b+ d+ e+ c+ a)
    print(    b+ e+ a+ c+ d)
    print(    b+ e+ a+ d+ c)
    print(    b+ e+ c+ a+ d)
    print(    b+ e+ c+ d+ a)
    print(    b+ e+ d+ a+ c)
    print(    b+ e+ d+ c+ a)
    print(    c+ a+ b+ d+ e)
    print(   c+ a+ b+ e+ d)
    print(    c+ a+ d+ b+ e)
    print(    c+ a+ d+ e+ b)
    print(    c+ a+ e+ b+ d)
    print(   c+ a+ e+ d+ b)
    print(    c+ b+ a+ d+ e)
    print(    c+ b+ a+ e+ d)
    print(    c+ b+ d+ a+ e)
    print(    c+ b+ d+ e+ a)
    print(    c+ b+ e+ a+ d)
    print(    c+ b+ e+ d+ a)
    print(    c+ d+ a+ b+ e)
    print(    c+ d+ a+ e+ b)
    print(    c+ d+ b+ a+ e)
    print(    c+ d+ b+ e+ a)
    print(    c+ d+ e+ a+ b)
    print(    c+ d+ e+ b+ a)
    print(    c+ e+ a+ b+ d)
    print(    c+ e+ a+ d+ b)
    print(    c+ e+ b+ a+ d)
    print(    c+ e+ b+ d+ a)
    print(    c+ e+ d+ a+ b)
    print(    c+ e+ d+ b+ a)
    print(    d+ a+ b+ c+ e)
    print(    d+ a+ b+ e+ c)
    print(    d+ a+ c+ b+ e)
    print(    d+ a+ c+ e+ b)
    print(    d+ a+ e+ b+ c)
    print(    d+ a+ e+ c+ b)
    print(    d+ b+ a+ c+ e)
    print(    d+ b+ a+ e+ c)
    print(    d+ b+ c+ a+ e)
    print(    d+ b+ c+ e+ a)
    print(    d+ b+ e+ a+ c)
    print(    d+ b+ e+ c+ a)
    print(    d+ c+ a+ b+ e)
    print(   d+ c+ a+ e+ b)
    print(    d+ c+ b+ a+ e)
    print(    d+ c+ b+ e+ a)
    print(    d+ c+ e+ a+ b)
    print(    d+ c+ e+ b+ a)
    print(    d+ e+ a+ b+ c)
    print(   d+ e+ a+ c+ b)
    print(    d+ e+ b+ a+ c)
    print(    d+ e+ b+ c+ a)
    print(    d+ e+ c+ a+ b)
    print(    d+ e+ c+ b+ a)
    print(    e+ a+ b+ c+ d)
    print(    e+ a+ b+ d+ c)
    print(    e+ a+ c+ b+ d)
    print(    e+ a+ c+ d+ b)
    print(    e+ a+ d+ b+ c)
    print(    e+ a+ d+ c+ b)
    print(    e+ b+ a+ c+ d)
    print(    e+ b+ a+ d+ c)
    print(    e+ b+ c+ a+ d)
    print(    e+ b+ c+ d+ a)
    print(    e+ b+ d+ a+ c)
    print(    e+ b+ d+ c+ a)
    print(    e+ c+ a+ b+ d)
    print(    e+ c+ a+ d+ b)
    print(    e+ c+ b+ a+ d)
    print(    e+ c+ b+ d+ a)
    print(    e+ c+ d+ a+ b)
    print(    e+ c+ d+ b+ a)
    print(    e+ d+ a+ b+ c)
    print(    e+ d+ a+ c+ b)
    print(    e+ d+ b+ a+ c)
    print(    e+ d+ b+ c+ a)
    print(    e+ d+ c+ a+ b)
    print(    e+ d+ c+ b+ a)
    print(    a+ b+ c+ d+ e+ f)
    print(    a+ b+ c+ d+ f+ e)
    print(    a+ b+ c+ e+ d+ f)
    print(    a+ b+ c+ e+ f+ d)
    print(    a+ b+ c+ f+ d+ e)
    print(    a+ b+ c+ f+ e+ d)
    print(    a+ b+ d+ c+ e+ f)
    print(    a+ b+ d+ c+ f+ e)
    print(    a+ b+ d+ e+ c+ f)
    print(    a+ b+ d+ e+ f+ c)
    print(    a+ b+ d+ f+ c+ e)
    print(    a+ b+ d+ f+ e+ c)
    print(   a+ b+ e+ c+ d+ f)
    print(   a+ b+ e+ c+ f+ d)
    print(    a+ b+ e+ d+ c+ f)
    print(    a+ b+ e+ d+ f+ c)
    print(    a+ b+ e+ f+ c+ d)
    print(    a+ b+ e+ f+ d+ c)
    print(    a+ b+ f+ c+ d+ e)
    print(    a+ b+ f+ c+ e+ d)
    print(    a+ b+ f+ d+ c+ e)
    print(    a+ b+ f+ d+ e+ c)
    print(    a+ b+ f+ e+ c+ d)
    print(    a+ b+ f+ e+ d+ c)
    print(    a+ c+ b+ d+ e+ f)
    print(    a+ c+ b+ d+ f+ e)
    print(    a+ c+ b+ e+ d+ f)
    print(    a+ c+ b+ e+ f+ d)
    print(    a+ c+ b+ f+ d+ e)
    print(    a+ c+ b+ f+ e+ d)
    print(    a+ c+ d+ b+ e+ f)
    print(    a+ c+ d+ b+ f+ e)
    print(    a+ c+ d+ e+ b+ f)
    print(    a+ c+ d+ e+ f+ b)
    print(    a+ c+ d+ f+ b+ e)
    print(    a+ c+ d+ f+ e+ b)
    print(    a+ c+ e+ b+ d+ f)
    print(    a+ c+ e+ b+ f+ d)
    print(    a+ c+ e+ d+ b+ f)
    print(    a+ c+ e+ d+ f+ b)
    print(    a+ c+ e+ f+ b+ d)
    print(    a+ c+ e+ f+ d+ b)
    print(     a+ c+ f+ b+ d+ e)
    print(    a+ c+ f+ b+ e+ d)
    print(    a+ c+ f+ d+ b+ e)
    print(    a+ c+ f+ d+ e+ b)
    print(    a+ c+ f+ e+ b+ d)
    print(    a+ c+ f+ e+ d+ b)
    print(    a+ d+ b+ c+ e+ f)
    print(    a+ d+ b+ c+ f+ e)
    print(    a+ d+ b+ e+ c+ f)
    print(    a+ d+ b+ e+ f+ c)
    print(    a+ d+ b+ f+ c+ e)
    print(    a+ d+ b+ f+ e+ c)
    print(    a+ d+ c+ b+ e+ f)
    print(   a+ d+ c+ b+ f+ e)
    print(    a+ d+ c+ e+ b+ f)
    print(    a+ d+ c+ e+ f+ b)
    print(    a+ d+ c+ f+ b+ e)
    print(    a+ d+ c+ f+ e+ b)
    print(    a+ d+ e+ b+ c+ f)
    print(    a+ d+ e+ b+ f+ c)
    print(    a+ d+ e+ c+ b+ f)
    print(    a+ d+ e+ c+ f+ b)
    print(    a+ d+ e+ f+ b+ c)
    print(    a+ d+ e+ f+ c+ b)
    print(    a+ d+ f+ b+ c+ e)
    print(    a+ d+ f+ b+ e+ c)
    print(    a+ d+ f+ c+ b+ e)
    print(    a+ d+ f+ c+ e+ b)
    print(    a+ d+ f+ e+ b+ c)
    print(    a+ d+ f+ e+ c+ b)
    print(    a+ e+ b+ c+ d+ f)
    print(    a+ e+ b+ c+ f+ d)
    print(    a+ e+ b+ d+ c+ f)
    print(    a+ e+ b+ d+ f+ c)
    print(    a+ e+ b+ f+ c+ d)
    print(    a+ e+ b+ f+ d+ c)
    print(    a+ e+ c+ b+ d+ f)
    print(    a+ e+ c+ b+ f+ d)
    print(    a+ e+ c+ d+ b+ f)
    print(    a+ e+ c+ d+ f+ b)
    print(    a+ e+ c+ f+ b+ d)
    print(    a+ e+ c+ f+ d+ b)
    print(    a+ e+ d+ b+ c+ f)
    print(    a+ e+ d+ b+ f+ c)
    print(    a+ e+ d+ c+ b+ f)
    print(    a+ e+ d+ c+ f+ b)
    print(    a+ e+ d+ f+ b+ c)
    print(    a+ e+ d+ f+ c+ b)
    print(    a+ e+ f+ b+ c+ d)
    print(    a+ e+ f+ b+ d+ c)
    print(    a+ e+ f+ c+ b+ d)
    print(    a+ e+ f+ c+ d+ b)
    print(    a+ e+ f+ d+ b+ c)
    print(    a+ e+ f+ d+ c+ b)
    print(    a+ f+ b+ c+ d+ e)
    print(    a+ f+ b+ c+ e+ d)
    print(   a+ f+ b+ d+ c+ e)
    print(    a+ f+ b+ d+ e+ c)
    print(    a+ f+ b+ e+ c+ d)
    print(    a+ f+ b+ e+ d+ c)
    print(    a+ f+ c+ b+ d+ e)
    print(    a+ f+ c+ b+ e+ d)
    print(    a+ f+ c+ d+ b+ e)
    print(    a+ f+ c+ d+ e+ b)
    print(    a+ f+ c+ e+ b+ d)
    print(    a+ f+ c+ e+ d+ b)
    print(    a+ f+ d+ b+ c+ e)
    print(    a+ f+ d+ b+ e+ c)
    print(    a+ f+ d+ c+ b+ e)
    print(    a+ f+ d+ c+ e+ b)
    print(    a+ f+ d+ e+ b+ c)
    print(    a+ f+ d+ e+ c+ b)
    print(    a+ f+ e+ b+ c+ d)
    print(    a+ f+ e+ b+ d+ c)
    print(    a+ f+ e+ c+ b+ d)
    print(    a+ f+ e+ c+ d+ b)
    print(    a+ f+ e+ d+ b+ c)
    print(    a+ f+ e+ d+ c+ b)
    print(    b+ a+ c+ d+ e+ f)
    print(    b+ a+ c+ d+ f+ e)
    print(    b+ a+ c+ e+ d+ f)
    print(    b+ a+ c+ e+ f+ d)
    print(    b+ a+ c+ f+ d+ e)
    print(    b+ a+ c+ f+ e+ d)
    print(    b+ a+ d+ c+ e+ f)
    print(    b+ a+ d+ c+ f+ e)
    print(    b+ a+ d+ e+ c+ f)
    print(    b+ a+ d+ e+ f+ c)
    print(    b+ a+ d+ f+ c+ e)
    print(    b+ a+ d+ f+ e+ c)
    print(    b+ a+ e+ c+ d+ f)
    print(    b+ a+ e+ c+ f+ d)
    print(    b+ a+ e+ d+ c+ f)
    print(    b+ a+ e+ d+ f+ c)
    print(    b+ a+ e+ f+ c+ d)
    print(    b+ a+ e+ f+ d+ c)
    print(    b+ a+ f+ c+ d+ e)
    print(    b+ a+ f+ c+ e+ d)
    print(    b+ a+ f+ d+ c+ e)
    print(    b+ a+ f+ d+ e+ c)
    print(    b+ a+ f+ e+ c+ d)
    print(    b+ a+ f+ e+ d+ c)
    print(    b+ c+ a+ d+ e+ f)
    print(    b+ c+ a+ d+ f+ e)
    print(    b+ c+ a+ e+ d+ f)
    print(    b+ c+ a+ e+ f+ d)
    print(    b+ c+ a+ f+ d+ e)
    print(    b+ c+ a+ f+ e+ d)
    print(    b+ c+ d+ a+ e+ f)
    print(    b+ c+ d+ a+ f+ e)
    print(    b+ c+ d+ e+ a+ f)
    print(    b+ c+ d+ e+ f+ a)
    print(    b+ c+ d+ f+ a+ e)
    print(    b+ c+ d+ f+ e+ a)
    print(    b+ c+ e+ a+ d+ f)
    print(    b+ c+ e+ a+ f+ d)
    print(    b+ c+ e+ d+ a+ f)
    print(    b+ c+ e+ d+ f+ a)
    print(    b+ c+ e+ f+ a+ d)
    print(    b+ c+ e+ f+ d+ a)
    print(    b+ c+ f+ a+ d+ e)
    print(   b+ c+ f+ a+ e+ d)
    print(    b+ c+ f+ d+ a+ e)
    print(    b+ c+ f+ d+ e+ a)
    print(    b+ c+ f+ e+ a+ d)
    print(    b+ c+ f+ e+ d+ a)
    print(    b+ d+ a+ c+ e+ f)
    print(    b+ d+ a+ c+ f+ e)
    print(    b+ d+ a+ e+ c+ f)
    print(    b+ d+ a+ e+ f+ c)
    print(    b+ d+ a+ f+ c+ e)
    print(    b+ d+ a+ f+ e+ c)
    print(    b+ d+ c+ a+ e+ f)
    print(    b+ d+ c+ a+ f+ e)
    print(    b+ d+ c+ e+ a+ f)
    print(     b+ d+ c+ e+ f+ a)
    print(    b+ d+ c+ f+ a+ e)
    print(    b+ d+ c+ f+ e+ a)
    print(    b+ d+ e+ a+ c+ f)
    print(    b+ d+ e+ a+ f+ c)
    print(    b+ d+ e+ c+ a+ f)
    print(    b+ d+ e+ c+ f+ a)
    print(    b+ d+ e+ f+ a+ c)
    print(    b+ d+ e+ f+ c+ a)
    print(    b+ d+ f+ a+ c+ e)
    print(   b+ d+ f+ a+ e+ c)
    print(    b+ d+ f+ c+ a+ e)
    print(    b+ d+ f+ c+ e+ a)
    print(    b+ d+ f+ e+ a+ c)
    print(    b+ d+ f+ e+ c+ a)
    print(    b+ e+ a+ c+ d+ f)
    print(    b+ e+ a+ c+ f+ d)
    print(    b+ e+ a+ d+ c+ f)
    print(    b+ e+ a+ d+ f+ c)
    print(    b+ e+ a+ f+ c+ d)
    print(   b+ e+ a+ f+ d+ c)
    print(    b+ e+ c+ a+ d+ f)
    print(    b+ e+ c+ a+ f+ d)
    print(    b+ e+ c+ d+ a+ f)
    print(    b+ e+ c+ d+ f+ a)
    print(    b+ e+ c+ f+ a+ d)
    print(    b+ e+ c+ f+ d+ a)
    print(    b+ e+ d+ a+ c+ f)
    print(    b+ e+ d+ a+ f+ c)
    print(    b+ e+ d+ c+ a+ f)
    print(    b+ e+ d+ c+ f+ a)
    print(    b+ e+ d+ f+ a+ c)
    print(   b+ e+ d+ f+ c+ a)
    print(    b+ e+ f+ a+ c+ d)
    print(    b+ e+ f+ a+ d+ c)
    print(    b+ e+ f+ c+ a+ d)
    print(    b+ e+ f+ c+ d+ a)
    print(    b+ e+ f+ d+ a+ c)
    print(    b+ e+ f+ d+ c+ a)
    print(    b+ f+ a+ c+ d+ e)
    print(    b+ f+ a+ c+ e+ d)
    print(    b+ f+ a+ d+ c+ e)
    print(    b+ f+ a+ d+ e+ c)
    print(    b+ f+ a+ e+ c+ d)
    print(    b+ f+ a+ e+ d+ c)
    print(    b+ f+ c+ a+ d+ e)
    print(    b+ f+ c+ a+ e+ d)
    print(    b+ f+ c+ d+ a+ e)
    print(    b+ f+ c+ d+ e+ a)
    print(    b+ f+ c+ e+ a+ d)
    print(    b+ f+ c+ e+ d+ a)
    print(    b+ f+ d+ a+ c+ e)
    print(    b+ f+ d+ a+ e+ c)
    print(    b+ f+ d+ c+ a+ e)
    print(    b+ f+ d+ c+ e+ a)
    print(    b+ f+ d+ e+ a+ c)
    print(    b+ f+ d+ e+ c+ a)
    print(    b+ f+ e+ a+ c+ d)
    print(    b+ f+ e+ a+ d+ c)
    print(    b+ f+ e+ c+ a+ d)
    print(    b+ f+ e+ c+ d+ a)
    print(    b+ f+ e+ d+ a+ c)
    print(    b+ f+ e+ d+ c+ a)
    print(    c+ a+ b+ d+ e+ f)
    print(    c+ a+ b+ d+ f+ e)
    print(    c+ a+ b+ e+ d+ f)
    print(    c+ a+ b+ e+ f+ d)
    print(    c+ a+ b+ f+ d+ e)
    print(    c+ a+ b+ f+ e+ d)
    print(    c+ a+ d+ b+ e+ f)
    print(    c+ a+ d+ b+ f+ e)
    print(    c+ a+ d+ e+ b+ f)
    print(    c+ a+ d+ e+ f+ b)
    print(    c+ a+ d+ f+ b+ e)
    print(    c+ a+ d+ f+ e+ b)
    print(   c+ a+ e+ b+ d+ f)
    print(    c+ a+ e+ b+ f+ d)
    print(    c+ a+ e+ d+ b+ f)
    print(    c+ a+ e+ d+ f+ b)
    print(    c+ a+ e+ f+ b+ d)
    print(    c+ a+ e+ f+ d+ b)
    print(    c+ a+ f+ b+ d+ e)
    print(    c+ a+ f+ b+ e+ d)
    print(    c+ a+ f+ d+ b+ e)
    print(    c+ a+ f+ d+ e+ b)
    print(    c+ a+ f+ e+ b+ d)
    print(    c+ a+ f+ e+ d+ b)
    print(    c+ b+ a+ d+ e+ f)
    print(   c+ b+ a+ d+ f+ e)
    print(    c+ b+ a+ e+ d+ f)
    print(    c+ b+ a+ e+ f+ d)
    print(    c+ b+ a+ f+ d+ e)
    print(    c+ b+ a+ f+ e+ d)
    print(    c+ b+ d+ a+ e+ f)
    print(    c+ b+ d+ a+ f+ e)
    print(    c+ b+ d+ e+ a+ f)
    print(    c+ b+ d+ e+ f+ a)
    print(    c+ b+ d+ f+ a+ e)
    print(    c+ b+ d+ f+ e+ a)
    print(    c+ b+ e+ a+ d+ f)
    print(    c+ b+ e+ a+ f+ d)
    print(    c+ b+ e+ d+ a+ f)
    print(    c+ b+ e+ d+ f+ a)
    print(    c+ b+ e+ f+ a+ d)
    print(    c+ b+ e+ f+ d+ a)
    print(    c+ b+ f+ a+ d+ e)
    print(   c+ b+ f+ a+ e+ d)
    print(    c+ b+ f+ d+ a+ e)
    print(    c+ b+ f+ d+ e+ a)
    print(    c+ b+ f+ e+ a+ d)
    print(    c+ b+ f+ e+ d+ a)
    print(    c+ d+ a+ b+ e+ f)
    print(    c+ d+ a+ b+ f+ e)
    print(    c+ d+ a+ e+ b+ f)
    print(    c+ d+ a+ e+ f+ b)
    print(    c+ d+ a+ f+ b+ e)
    print(    c+ d+ a+ f+ e+ b)
    print(    c+ d+ b+ a+ e+ f)
    print(    c+ d+ b+ a+ f+ e)
    print(    c+ d+ b+ e+ a+ f)
    print(    c+ d+ b+ e+ f+ a)
    print(    c+ d+ b+ f+ a+ e)
    print(    c+ d+ b+ f+ e+ a)
    print(    c+ d+ e+ a+ b+ f)
    print(    c+ d+ e+ a+ f+ b)
    print(    c+ d+ e+ b+ a+ f)
    print(    c+ d+ e+ b+ f+ a)
    print(    c+ d+ f+ b+ a+ e)
    print(    c+ d+ e+ f+ a+ b)
    print(    c+ d+ e+ f+ b+ a)
    print(    c+ d+ f+ a+ b+ e)
    print(    c+ d+ f+ a+ e+ b)
    print(    c+ d+ f+ b+ a+ e)
    print(    c+ d+ f+ b+ e+ a)
    print(    c+ d+ f+ e+ a+ b)
    print(    c+ d+ f+ e+ b+ a)
    print(    c+ e+ a+ b+ d+ f)
    print(    c+ e+ a+ b+ f+ d)
    print(    c+ e+ a+ d+ b+ f)
    print(    c+ e+ a+ d+ f+ b)
    print(    c+ e+ a+ f+ b+ d)
    print(    c+ e+ a+ f+ d+ b)
    print(    c+ e+ b+ a+ d+ f)
    print(   c+ e+ b+ a+ f+ d)
    print(    c+ e+ b+ d+ a+ f)
    print(    c+ e+ b+ d+ f+ a)
    print(    c+ e+ b+ f+ a+ d)
    print(    c+ e+ b+ f+ d+ a)
    print(    c+ e+ d+ a+ b+ f)
    print(    c+ e+ d+ a+ f+ b)
    print(    c+ e+ d+ b+ a+ f)
    print(    c+ e+ d+ b+ f+ a)
    print(    c+ e+ d+ f+ a+ b)
    print(    c+ e+ d+ f+ b+ a)
    print(    c+ e+ f+ a+ b+ d)
    print(    c+ e+ f+ a+ d+ b)
    print(   c+ e+ f+ b+ a+ d)
    print(    c+ e+ f+ b+ d+ a)
    print(    c+ e+ f+ d+ a+ b)
    print(    c+ e+ f+ d+ b+ a)
    print(    c+ f+ a+ b+ d+ e)
    print(    c+ f+ a+ b+ e+ d)
    print(    c+ f+ a+ d+ b+ e)
    print(    c+ f+ a+ d+ e+ b)
    print(    c+ f+ a+ e+ b+ d)
    print(    c+ f+ a+ e+ d+ b)
    print(    c+ f+ b+ a+ d+ e)
    print(    c+ f+ b+ a+ e+ d)
    print(    c+ f+ b+ d+ a+ e)
    print(    c+ f+ b+ d+ e+ a)
    print(    c+ f+ b+ e+ a+ d)
    print(    c+ f+ b+ e+ d+ a)
    print(    c+ f+ d+ a+ b+ e)
    print(    c+ f+ d+ a+ e+ b)
    print(    c+ f+ d+ b+ a+ e)
    print(    c+ f+ d+ b+ e+ a)
    print(    c+ f+ d+ e+ a+ b)
    print(    c+ f+ d+ e+ b+ a)
    print(    c+ f+ e+ a+ b+ d)
    print(    c+ f+ e+ a+ d+ b)
    print(    c+ f+ e+ b+ a+ d)
    print(    c+ f+ e+ b+ d+ a)
    print(    c+ f+ e+ d+ a+ b)
    print(    c+ f+ e+ d+ b+ a)
    print(    d+ a+ b+ c+ e+ f)
    print(    d+ a+ b+ c+ f+ e)
    print(    d+ a+ b+ e+ c+ f)
    print(    d+ a+ b+ e+ f+ c)
    print(    d+ a+ b+ f+ c+ e)
    print(    d+ a+ b+ f+ e+ c)
    print(    d+ a+ c+ b+ e+ f)
    print(    d+ a+ c+ b+ f+ e)
    print(    d+ a+ c+ e+ b+ f)
    print(    d+ a+ c+ e+ f+ b)
    print(    d+ a+ c+ f+ b+ e)
    print(    d+ a+ c+ f+ e+ b)
    print(    d+ a+ e+ b+ c+ f)
    print(    d+ a+ e+ b+ f+ c)
    print(    d+ a+ e+ c+ b+ f)
    print(    d+ a+ e+ c+ f+ b)
    print(    d+ a+ e+ f+ b+ c)
    print(    d+ a+ e+ f+ c+ b)
    print(    d+ a+ f+ b+ c+ e)
    print(    d+ a+ f+ b+ e+ c)
    print(    d+ a+ f+ c+ b+ e)
    print(    d+ a+ f+ c+ e+ b)
    print(    d+ a+ f+ e+ b+ c)
    print(    d+ a+ f+ e+ c+ b)
    print(    d+ b+ a+ c+ e+ f)
    print(    d+ b+ a+ c+ f+ e)
    print(    d+ b+ a+ e+ c+ f)
    print(    d+ b+ a+ e+ f+ c)
    print(    d+ b+ a+ f+ c+ e)
    print(    d+ b+ a+ f+ e+ c)
    print(    d+ b+ c+ a+ e+ f)
    print(    d+ b+ c+ a+ f+ e)
    print(    d+ b+ c+ e+ a+ f)
    print(    d+ b+ c+ e+ f+ a)
    print(    d+ b+ c+ f+ a+ e)
    print(    d+ b+ c+ f+ e+ a)
    print(    d+ b+ e+ a+ c+ f)
    print(    d+ b+ e+ a+ f+ c)
    print(    d+ b+ e+ c+ a+ f)
    print(    d+ b+ e+ c+ f+ a)
    print(    d+ b+ e+ f+ a+ c)
    print(    d+ b+ e+ f+ c+ a)
    print(    d+ b+ f+ a+ c+ e)
    print(    d+ b+ f+ a+ e+ c)
    print(    d+ b+ f+ c+ a+ e)
    print(    d+ b+ f+ c+ e+ a)
    print(    d+ b+ f+ e+ a+ c)
    print(    d+ b+ f+ e+ c+ a)
    print(    d+ c+ a+ b+ e+ f)
    print(    d+ c+ a+ b+ f+ e)
    print(    d+ c+ a+ e+ b+ f)
    print(    d+ c+ a+ e+ f+ b)
    print(    d+ c+ a+ f+ b+ e)
    print(    d+ c+ a+ f+ e+ b)
    print(    d+ c+ b+ a+ e+ f)
    print(    d+ c+ b+ a+ f+ e)
    print(    d+ c+ b+ e+ a+ f)
    print(    d+ c+ b+ e+ f+ a)
    print(    d+ c+ b+ f+ a+ e)
    print(    d+ c+ b+ f+ e+ a)
    print(    d+ c+ e+ a+ b+ f)
    print(    d+ c+ e+ a+ f+ b)
    print(    d+ c+ e+ b+ a+ f)
    print(    d+ c+ e+ b+ f+ a)
    print(    d+ c+ e+ f+ a+ b)
    print(    d+ c+ e+ f+ b+ a)
    print(    d+ c+ f+ a+ b+ e)
    print(    d+ c+ f+ a+ e+ b)
    print(    d+ c+ f+ b+ a+ e)
    print(    d+ c+ f+ b+ e+ a)
    print(    d+ c+ f+ e+ a+ b)
    print(    d+ c+ f+ e+ b+ a)
    print(    d+ e+ a+ b+ c+ f)
    print(    d+ e+ a+ b+ f+ c)
    print(    d+ e+ a+ c+ b+ f)
    print(    d+ e+ a+ c+ f+ b)
    print(    d+ e+ a+ f+ b+ c)
    print(    d+ e+ a+ f+ c+ b)
    print(    d+ e+ b+ a+ c+ f)
    print(    d+ e+ b+ a+ f+ c)
    print(    d+ e+ b+ c+ a+ f)
    print(    d+ e+ b+ c+ f+ a)
    print(    d+ e+ b+ f+ a+ c)
    print(    d+ e+ b+ f+ c+ a)
    print(    d+ e+ c+ a+ b+ f)
    print(    d+ e+ c+ a+ f+ b)
    print(    d+ e+ c+ b+ a+ f)
    print(    d+ e+ c+ b+ f+ a)
    print(    d+ e+ c+ f+ a+ b)
    print(    d+ e+ c+ f+ b+ a)
    print(    d+ e+ f+ a+ b+ c)
    print(    d+ e+ f+ a+ c+ b)
    print(    d+ e+ f+ b+ a+ c)
    print(    d+ e+ f+ b+ c+ a)
    print(    d+ e+ f+ c+ a+ b)
    print(    d+ e+ f+ c+ b+ a)
    print(    d+ f+ a+ b+ c+ e)
    print(    d+ f+ a+ b+ e+ c)
    print(    d+ f+ a+ c+ b+ e)
    print(    d+ f+ a+ c+ e+ b)
    print(    d+ f+ a+ e+ b+ c)
    print(    d+ f+ a+ e+ c+ b)
    print(    d+ f+ b+ a+ c+ e)
    print(    d+ f+ b+ a+ e+ c)
    print(    d+ f+ b+ c+ a+ e)
    print(    d+ f+ b+ c+ e+ a)
    print(    d+ f+ b+ e+ a+ c)
    print(    d+ f+ b+ e+ c+ a)
    print(    d+ f+ c+ a+ b+ e)
    print(    d+ f+ c+ a+ e+ b)
    print(    d+ f+ c+ b+ a+ e)
    print(    d+ f+ c+ b+ e+ a)
    print(    d+ f+ c+ e+ a+ b)
    print(    d+ f+ c+ e+ b+ a)
    print(    d+ f+ e+ a+ b+ c)
    print(    d+ f+ e+ a+ c+ b)
    print(    d+ f+ e+ b+ a+ c)
    print(    d+ f+ e+ b+ c+ a)
    print(    d+ f+ e+ c+ a+ b)
    print(    d+ f+ e+ c+ b+ a)
    print(    e+ a+ b+ c+ d+ f)
    print(    e+ a+ b+ c+ f+ d)
    print(    e+ a+ b+ d+ c+ f)
    print(    e+ a+ b+ d+ f+ c)
    print(    e+ a+ b+ f+ c+ d)
    print(    e+ a+ b+ f+ d+ c)
    print(    e+ a+ c+ b+ d+ f)
    print(    e+ a+ c+ b+ f+ d)
    print(    e+ a+ c+ d+ b+ f)
    print(    e+ a+ c+ d+ f+ b)
    print(   e+ a+ c+ f+ b+ d)
    print(    e+ a+ c+ f+ d+ b)
    print(    e+ a+ d+ b+ c+ f)
    print(    e+ a+ d+ b+ f+ c)
    print(    e+ a+ d+ c+ b+ f)
    print(    e+ a+ d+ c+ f+ b)
    print(    e+ a+ d+ f+ b+ c)
    print(    e+ a+ d+ f+ c+ b)
    print(    e+ a+ f+ b+ c+ d)
    print(    e+ a+ f+ b+ d+ c)
    print(    e+ a+ f+ c+ b+ d)
    print(    e+ a+ f+ c+ d+ b)
    print(    e+ a+ f+ d+ b+ c)
    print(    e+ a+ f+ d+ c+ b)
    print(    e+ b+ a+ c+ d+ f)
    print(    e+ b+ a+ c+ f+ d)
    print(    e+ b+ a+ d+ c+ f)
    print(    e+ b+ a+ d+ f+ c)
    print(    e+ b+ a+ f+ c+ d)
    print(    e+ b+ a+ f+ d+ c)
    print(    e+ b+ c+ a+ d+ f)
    print(    e+ b+ c+ a+ f+ d)
    print(    e+ b+ c+ d+ a+ f)
    print(    e+ b+ c+ d+ f+ a)
    print(    e+ b+ c+ f+ a+ d)
    print(    e+ b+ c+ f+ d+ a)
    print(    e+ b+ d+ a+ c+ f)
    print(    e+ b+ d+ a+ f+ c)
    print(    e+ b+ d+ c+ a+ f)
    print(    e+ b+ d+ c+ f+ a)
    print(    e+ b+ d+ f+ a+ c)
    print(    e+ b+ d+ f+ c+ a)
    print(    e+ b+ f+ a+ c+ d)
    print(    e+ b+ f+ a+ d+ c)
    print(    e+ b+ f+ c+ a+ d)
    print(    e+ b+ f+ c+ d+ a)
    print(    e+ b+ f+ d+ a+ c)
    print(    e+ b+ f+ d+ c+ a)
    print(    e+ c+ a+ b+ d+ f)
    print(    e+ c+ a+ b+ f+ d)
    print(    e+ c+ a+ d+ b+ f)
    print(    e+ c+ a+ d+ f+ b)
    print(    e+ c+ a+ f+ b+ d)
    print(    e+ c+ a+ f+ d+ b)
    print(    e+ c+ b+ a+ d+ f)
    print(    e+ c+ b+ a+ f+ d)
    print(    e+ c+ b+ d+ a+ f)
    print(    e+ c+ b+ d+ f+ a)
    print(    e+ c+ b+ f+ a+ d)
    print(    e+ c+ b+ f+ d+ a)
    print(    e+ c+ d+ a+ b+ f)
    print(    e+ c+ d+ a+ f+ b)
    print(    e+ c+ d+ b+ a+ f)
    print(    e+ c+ d+ b+ f+ a)
    print(    e+ c+ d+ f+ a+ b)
    print(    e+ c+ d+ f+ b+ a)
    print(    e+ c+ f+ a+ b+ d)
    print(    e+ c+ f+ a+ d+ b)
    print(    e+ c+ f+ b+ a+ d)
    print(    e+ c+ f+ b+ d+ a)
    print(    e+ c+ f+ d+ a+ b)
    print(    e+ c+ f+ d+ b+ a)
    print(    e+ d+ a+ b+ c+ f)
    print(    e+ d+ a+ b+ f+ c)
    print(    e+ d+ a+ c+ b+ f)
    print(    e+ d+ a+ c+ f+ b)
    print(    e+ d+ a+ f+ b+ c)
    print(    e+ d+ a+ f+ c+ b)
    print(    e+ d+ b+ a+ c+ f)
    print(    e+ d+ b+ a+ f+ c)
    print(    e+ d+ b+ c+ a+ f)
    print(    e+ d+ b+ c+ f+ a)
    print(    e+ d+ b+ f+ a+ c)
    print(    e+ d+ b+ f+ c+ a)
    print(    e+ d+ c+ a+ b+ f)
    print(    e+ d+ c+ a+ f+ b)
    print(    e+ d+ c+ b+ a+ f)
    print(    e+ d+ c+ b+ f+ a)
    print(    e+ d+ c+ f+ a+ b)
    print(    e+ d+ c+ f+ b+ a)
    print(    e+ d+ f+ a+ b+ c)
    print(    e+ d+ f+ a+ c+ b)
    print(    e+ d+ f+ b+ a+ c)
    print(    e+ d+ f+ b+ c+ a)
    print(    e+ d+ f+ c+ a+ b)
    print(    e+ d+ f+ c+ b+ a)
    print(    e+ f+ a+ b+ c+ d)
    print(    e+ f+ a+ b+ d+ c)
    print(    e+ f+ a+ c+ b+ d)
    print(    e+ f+ a+ c+ d+ b)
    print(    e+ f+ a+ d+ b+ c)
    print(    e+ f+ a+ d+ c+ b)
    print(    e+ f+ b+ a+ c+ d)
    print(    e+ f+ b+ a+ d+ c)
    print(    e+ f+ b+ c+ a+ d)
    print(    e+ f+ b+ c+ d+ a)
    print(    e+ f+ b+ d+ a+ c)
    print(    e+ f+ b+ d+ c+ a)
    print(    e+ f+ c+ a+ b+ d)
    print(    e+ f+ c+ a+ d+ b)
    print(    e+ f+ c+ b+ a+ d)
    print(    e+ f+ c+ b+ d+ a)
    print(    e+ f+ c+ d+ a+ b)
    print(    e+ f+ c+ d+ b+ a)
    print(    e+ f+ d+ a+ b+ c)
    print(    e+ f+ d+ a+ c+ b)
    print(    e+ f+ d+ b+ a+ c)
    print(    e+ f+ d+ b+ c+ a)
    print(    e+ f+ d+ c+ a+ b)
    print(    e+ f+ d+ c+ b+ a)
    print(    f+ a+ b+ c+ d+ e)
    print(    f+ a+ b+ c+ e+ d)
    print(    f+ a+ b+ d+ c+ e)
    print(    f+ a+ b+ d+ e+ c)
    print(    f+ a+ b+ e+ c+ d)
    print(    f+ a+ b+ e+ d+ c)
    print(    f+ a+ c+ b+ d+ e)
    print(    f+ a+ c+ b+ e+ d)
    print(    f+ a+ c+ d+ b+ e)
    print(    f+ a+ c+ d+ e+ b)
    print(    f+ a+ c+ e+ b+ d)
    print(    f+ a+ c+ e+ d+ b)
    print(    f+ a+ d+ b+ c+ e)
    print(    f+ a+ d+ b+ e+ c)
    print(    f+ a+ d+ c+ b+ e)
    print(    f+ a+ d+ c+ e+ b)
    print(    f+ a+ d+ e+ b+ c)
    print(    f+ a+ d+ e+ c+ b)
    print(    f+ a+ e+ b+ c+ d)
    print(    f+ a+ e+ b+ d+ c)
    print(    f+ a+ e+ c+ b+ d)
    print(    f+ a+ e+ c+ d+ b)
    print(    f+ a+ e+ d+ b+ c)
    print(    f+ a+ e+ d+ c+ b)
    print(    f+ b+ a+ c+ d+ e)
    print(    f+ b+ a+ c+ e+ d)
    print(    f+ b+ a+ d+ c+ e)
    print(    f+ b+ a+ d+ e+ c)
    print(    f+ b+ a+ e+ c+ d)
    print(    f+ b+ a+ e+ d+ c)
    print(    f+ b+ c+ a+ d+ e)
    print(    f+ b+ c+ a+ e+ d)
    print(    f+ b+ c+ d+ a+ e)
    print(    f+ b+ c+ d+ e+ a)
    print(    f+ b+ c+ e+ a+ d)
    print(    f+ b+ c+ e+ d+ a)
    print(    f+ b+ d+ a+ c+ e)
    print(    f+ b+ d+ a+ e+ c)
    print(    f+ b+ d+ c+ a+ e)
    print(    f+ b+ d+ c+ e+ a)
    print(    f+ b+ d+ e+ a+ c)
    print(    f+ b+ d+ e+ c+ a)
    print(    f+ b+ e+ a+ c+ d)
    print(    f+ b+ e+ a+ d+ c)
    print(    f+ b+ e+ c+ a+ d)
    print(    f+ b+ e+ c+ d+ a)
    print(    f+ b+ e+ d+ a+ c)
    print(    f+ b+ e+ d+ c+ a)
    print(    f+ c+ a+ b+ d+ e)
    print(    f+ c+ a+ b+ e+ d)
    print(    f+ c+ a+ d+ b+ e)
    print(    f+ c+ a+ d+ e+ b)
    print(    f+ c+ a+ e+ b+ d)
    print(    f+ c+ a+ e+ d+ b)
    print(    f+ c+ b+ a+ d+ e)
    print(    f+ c+ b+ a+ e+ d)
    print(    f+ c+ b+ d+ a+ e)
    print(    f+ c+ b+ d+ e+ a)
    print(    f+ c+ b+ e+ a+ d)
    print(    f+ c+ b+ e+ d+ a)
    print(    f+ c+ d+ a+ b+ e)
    print(    f+ c+ d+ a+ e+ b)
    print(    f+ c+ d+ b+ a+ e)
    print(    f+ c+ d+ b+ e+ a)
    print(    f+ c+ d+ e+ a+ b)
    print(    f+ c+ d+ e+ b+ a)
    print(    f+ c+ e+ a+ b+ d)
    print(    f+ c+ e+ a+ d+ b)
    print(    f+ c+ e+ b+ a+ d)
    print(    f+ c+ e+ b+ d+ a)
    print(    f+ c+ e+ d+ a+ b)
    print(    f+ c+ e+ d+ b+ a)
    print(   f+ d+ a+ b+ c+ e)
    print(    f+ d+ a+ b+ e+ c)
    print(    f+ d+ a+ c+ b+ e)
    print(    f+ d+ a+ c+ e+ b)
    print(     f+ d+ a+ e+ b+ c)
    print(    f+ d+ a+ e+ c+ b)
    print(    f+ d+ b+ a+ c+ e)
    print(    f+ d+ b+ a+ e+ c)
    print(    f+ d+ b+ c+ a+ e)
    print(    f+ d+ b+ c+ e+ a)
    print(    f+ d+ b+ e+ a+ c)
    print(    f+ d+ b+ e+ c+ a)
    print(    f+ d+ c+ a+ b+ e)
    print(    f+ d+ c+ a+ e+ b)
    print(    f+ d+ c+ b+ a+ e)
    print(    f+ d+ c+ b+ e+ a)
    print(    f+ d+ c+ e+ a+ b)
    print(    f+ d+ c+ e+ b+ a)
    print(    f+ d+ e+ a+ b+ c)
    print(    f+ d+ e+ a+ c+ b)
    print(    f+ d+ e+ b+ a+ c)
    print(    f+ d+ e+ b+ c+ a)
    print(    f+ d+ e+ c+ a+ b)
    print(    f+ d+ e+ c+ b+ a)
    print(    f+ e+ a+ b+ c+ d)
    print(    f+ e+ a+ b+ d+ c)
    print(    f+ e+ a+ c+ b+ d)
    print(    f+ e+ a+ c+ d+ b)
    print(    f+ e+ a+ d+ b+ c)
    print(    f+ e+ a+ d+ c+ b)
    print(    f+ e+ b+ a+ c+ d)
    print(    f+ e+ b+ a+ d+ c)
    print(    f+ e+ b+ c+ a+ d)
    print(    f+ e+ b+ c+ d+ a)
    print(    f+ e+ b+ d+ a+ c)
    print(    f+ e+ b+ d+ c+ a)
    print(    f+ e+ c+ a+ b+ d)
    print(    f+ e+ c+ a+ d+ b)
    print(    f+ e+ c+ b+ a+ d)
    print(    f+ e+ c+ b+ d+ a)
    print(    f+ e+ c+ d+ a+ b)
    print(    f+ e+ c+ d+ b+ a)
    print(    f+ e+ d+ a+ b+ c)
    print(    f+ e+ d+ a+ c+ b)
    print(    f+ e+ d+ b+ a+ c)
    print(    f+ e+ d+ b+ c+ a)
    print(    f+ e+ d+ c+ a+ b)
    print(    f+ e+ d+ c+ b+ a)